# compose.aws.yml (Production Override)
# This file overrides the base docker-compose.yml for AWS deployment.
# It switches services from using local builds to pulling pre-built images from GHCR.

services:
  client:
    image: ghcr.io/aet-devops25/team-dev_ops/client:latest
    build: null # Explicitly disable the build

  api-server:
    image: ghcr.io/aet-devops25/team-dev_ops/api-server:latest
    build: null # Explicitly disable the build

  genai:
    image: ghcr.io/aet-devops25/team-dev_ops/genai:latest
    build: null # Explicitly disable the build

  topic-discovery:
    image: ghcr.io/aet-devops25/team-dev_ops/topic-discovery:latest
    build: null # Explicitly disable the build

  article-fetcher:
    image: ghcr.io/aet-devops25/team-dev_ops/article-fetcher:latest
    build: null # Explicitly disable the build