{
 "title": "Niche Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overall Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Rates - Timeseries Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "traefik_requests_sum_by_service_4xx",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - Timeseries Panels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "traefik_requests_histogram_quantile_for_95th_percentile_by_entrypoints",
     "legendFormat": "__auto"
    },
    {
     "expr": "traefik_requests_histogram_quantile_for_95th_percentile_by_service",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rates - Timeseries Panels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "traefik_requests_sum_by_entrypoint_rate",
     "legendFormat": "__auto"
    },
    {
     "expr": "traefik_requests_sum_by_service",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Key Performance Indicators - Stat Panels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(traefik_requests_sum_by_entrypoint_rate)",
     "legendFormat": "__auto"
    },
    {},
    {
     "expr": "traefik_requests_histogram_quantile_for_95th_percentile",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_requests_sum_by_service_4xx)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}